// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ENTIDADES
{
    public partial class Monografias
    {
        public int IdPublicacion { get; set; }
        public string NombreMono { get; set; }

        public virtual Publicaciones IdPublicacionNavigation { get; set; }
    }
}