// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ENTIDADES
{
    public partial class Prestamo
    {
        public int IdPrestamo { get; set; }
        public DateTime FechaInicioPrestamo { get; set; }
        public DateTime FechaDevolucion { get; set; }
        public int? IdUsuario { get; set; }

        public virtual Usuarios IdUsuarioNavigation { get; set; }
    }
}