// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ENTIDADES
{
    public partial class Publicaciones
    {
        public int IdPublicacion { get; set; }
        public string Titulo { get; set; }
        public int NumEjemplar { get; set; }

        public virtual Monografias Monografias { get; set; }
        public virtual Revistas Revistas { get; set; }
        public virtual Textos Textos { get; set; }
    }
}