// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ENTIDADES
{
    public partial class Textos
    {
        public int IdPublicacion { get; set; }
        public string Autor { get; set; }
        public string Editorial { get; set; }
        public int NumPaginas { get; set; }

        public virtual Publicaciones IdPublicacionNavigation { get; set; }
    }
}