// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ENTIDADES
{
    public partial class Usuarios
    {
        public Usuarios()
        {
            Prestamo = new HashSet<Prestamo>();
        }

        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Colonia { get; set; }
        public int Numero { get; set; }
        public int Cp { get; set; }
        public string NomCentroTrabajo { get; set; }
        public string Telefono { get; set; }

        public virtual ICollection<Prestamo> Prestamo { get; set; }
    }
}